#+TITLE: Alazzza

[[https://github.com/alazzza/alazzza.github.io/edit/main/src/index.org][Edit]]

-----

* ???
:PROPERTIES:
:CUSTOM_ID: about
:END:

My personal notes on various topics.

DISCLAIMER: This website's information is not meant to be a diagnostic aid or source of medical advice. You should consult a doctor if you have a medical issue. 

I am a newly qualified medical doctor. If you have a topic which you would like me to cover, please contact me.

Disclaimer 1: nothing, and I do mean /nothing/, on this website is intended as medical advice. If you have a medical issue, you must seek medical advice rather than consult the internet.

Disclaimer 2: I do this in my limited spare time after work. So, although I try my absolute best ensure that the content is accurate, there may be mistakes. Refer to the resources listed at the end of each topic!

Unless otherwise stated, everything on the site is under the [[https://raw.githubusercontent.com/alazzza/alazzza.github.io/refs/heads/main/LICENSE][GPL-3.0 license]].


* Subjects
:PROPERTIES:
:CUSTOM_ID: subjects
:END:

- [[file:./ent/index.org][ENT]]
- [[file:./ugi/index.org][Upper GI]]

